# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170925_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePhoto',
        ),
    ]
